[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "estatistica-lab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-tidyverse = ">=2.0.0,<3"
r-conflicted = ">=1.2.0,<2"
rstudio-desktop = "*"
r-pak = ">=0.8.0,<0.9"
r-janitor = ">=2.2.0,<3"
