[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "estatistica-lab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-tidyverse = ">=2.0.0,<3"
r-conflicted = ">=1.2.0,<2"
rstudio-desktop = ">=2024.4.2,<2025"
